# Site Settings
title: Portfolio Theme
email: denisvieira05@gmail.com
description: "Thinker // Designer // Youtuber"

# Build settings

markdown: kramdown
permalink: pretty

port: 4000

sass:
  sass_dir: assets/css
  style: :compressed